CREATE TABLE U_NAME (
	UUID VARCHAR(36) NOT NULL,
    NAME VARCHAR(16) NOT NULL,
    SEE DATETIME NOT NULL DEFAULT NOW()
) ENGINE = InnoDB COLLATE utf8mb4_bin;

CREATE TABLE U_ACTIVITY (
	UUID VARCHAR(36) NOT NULL,
    ISJOIN BOOLEAN NOT NULL,
    A_WHEN DATETIME NOT NULL DEFAULT NOW()
) ENGINE = InnoDB COLLATE utf8mb4_bin;

DELIMITER $$
CREATE PROCEDURE CN(UUID VARCHAR(36), NAME VARCHAR(16)) 
BEGIN
	IF UPPER(COALESCE((SELECT X.NAME FROM U_NAME AS X WHERE UUID = X.UUID ORDER BY SEE LIMIT 1), "")) <> UPPER(NAME) THEN
		INSERT U_NAME (UUID, NAME) VALUE (UUID, NAME);
    END IF;
END $$