USE SAGMC;

CREATE TABLE U_NAME (
	UUID VARCHAR(36) NOT NULL,
    NAME VARCHAR(16) NOT NULL,
    SEE DATETIME NOT NULL DEFAULT NOW()
) ENGINE = InnoDB COLLATE utf8mb4_bin;

CREATE TABLE U_ACTIVITY (
	UUID VARCHAR(36) NOT NULL,
    ISJOIN BOOLEAN NOT NULL,
    A_WHEN DATETIME NOT NULL DEFAULT NOW()
) ENGINE = InnoDB COLLATE utf8mb4_bin;

DELIMITER $$
CREATE PROCEDURE CN(UUID VARCHAR(36), NAME VARCHAR(16)) 
BEGIN
	IF UPPER(COALESCE((SELECT X.NAME FROM U_NAME AS X WHERE UUID = X.UUID AND SEE = (SELECT MAX(SEE) FROM U_NAME AS X WHERE UUID = X.UUID GROUP BY X.UUID)), "")) <> UPPER(NAME) THEN
		INSERT U_NAME (UUID, NAME) VALUE (UUID, NAME);
    END IF;
END $$

DELIMITER $$
CREATE PROCEDURE CA(UUID VARCHAR(36), ISJOIN BOOLEAN) 
BEGIN
	IF (SELECT (SELECT UUID FROM U_ACTIVITY AS X WHERE UUID = X.UUID AND X.ISJOIN = ISJOIN AND A_WHEN = NOW()) IS NULL) THEN
		INSERT U_ACTIVITY (UUID, ISJOIN) VALUES (UUID, ISJOIN);
    END IF;
END $$